# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sphere_editor.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(521, 678)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.left_layout = QtWidgets.QVBoxLayout()
        self.left_layout.setObjectName("left_layout")
        self.add_button = QtWidgets.QPushButton(self.centralwidget)
        self.add_button.setObjectName("add_button")
        self.left_layout.addWidget(self.add_button)
        self.remove_button = QtWidgets.QPushButton(self.centralwidget)
        self.remove_button.setObjectName("remove_button")
        self.left_layout.addWidget(self.remove_button)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.radius_label = QtWidgets.QLabel(self.centralwidget)
        self.radius_label.setObjectName("radius_label")
        self.horizontalLayout_3.addWidget(self.radius_label)
        self.radius_spinbox = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.radius_spinbox.setDecimals(3)
        self.radius_spinbox.setMaximum(1.0)
        self.radius_spinbox.setSingleStep(0.001)
        self.radius_spinbox.setStepType(QtWidgets.QAbstractSpinBox.DefaultStepType)
        self.radius_spinbox.setObjectName("radius_spinbox")
        self.horizontalLayout_3.addWidget(self.radius_spinbox)
        self.left_layout.addLayout(self.horizontalLayout_3)
        self.save_button = QtWidgets.QPushButton(self.centralwidget)
        self.save_button.setObjectName("save_button")
        self.left_layout.addWidget(self.save_button)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.left_layout.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.left_layout)
        self.spheres_tree = QtWidgets.QTreeWidget(self.centralwidget)
        self.spheres_tree.setColumnCount(4)
        self.spheres_tree.setObjectName("spheres_tree")
        self.spheres_tree.headerItem().setText(0, "1")
        self.spheres_tree.headerItem().setText(1, "2")
        self.spheres_tree.headerItem().setText(2, "3")
        self.spheres_tree.headerItem().setText(3, "4")
        self.spheres_tree.header().setVisible(True)
        self.spheres_tree.header().setCascadingSectionResizes(True)
        self.spheres_tree.header().setDefaultSectionSize(120)
        self.spheres_tree.header().setStretchLastSection(False)
        self.horizontalLayout.addWidget(self.spheres_tree)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.add_button.setText(_translate("MainWindow", "Add Sphere"))
        self.remove_button.setText(_translate("MainWindow", "Remove Sphere"))
        self.radius_label.setText(_translate("MainWindow", "Radius"))
        self.save_button.setText(_translate("MainWindow", "Save"))
